Repository vearch/vearch, pull requests merged in 2024-03, with the labels that each got.

#761 Update doc_resp.go
  internal/router/document/doc_resp.go
Labels: size:S

#763 Delete internal/monitor/whh_test.go
  internal/monitor/whh_test.go
Labels: size:M

#762 Update doc_http.go
  internal/router/document/doc_http.go
Labels: size:M

#764 Create db_test.go
  internal/entity/db_test.go
Labels: size:M

#765 Update compile.sh
  cloud/compile/compile.sh
Labels: size:XS
