Repository vearch/vearch, pull requests merged in 2024-02, with the labels that each got.

#756 Delete tools/deployment directory
  tools/deployment/README.md
  tools/deployment/batch_deployment.go
  tools/deployment/demo/conf.json
  tools/deployment/demo/config.toml
  tools/deployment/demo/deploy.sh
  tools/deployment/demo/start.sh
  tools/deployment/demo/stop.sh
Labels: size:XL

#757 Delete docs/api directory
  docs/api/master_db_space.md
  docs/api/master_util.md
  docs/api/router_aggregation.md
  docs/api/router_document.md
  docs/api/router_query.md
  docs/api/router_util.md
Labels: size:L

#758 Update README.md
  README.md
Labels: size:M

#759 Update README.md
  README.md
Labels: size:XS

#760 readme提交
  README.md
  README_ZH_CN.md
Labels: size:L
